# Generated by Django 3.1.6 on 2021-05-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ccompanyname', models.TextField(default='')),
                ('Aaddress', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bbackground', models.TextField(default='')),
                ('Ccapabilities', models.TextField(default='')),
                ('Accreditations', models.TextField(default='')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RPList.company')),
            ],
        ),
        migrations.CreateModel(
            name='Jobinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jjobtitle', models.TextField(default='')),
                ('Jjobvacancy', models.TextField(default='')),
                ('Jjobskillsandqualifications', models.TextField(default='')),
                ('Pposition', models.TextField(default='')),
                ('Jjobresponsibilities', models.TextField(default='')),
                ('Jjobsalary', models.TextField(default='')),
                ('companyinfo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RPList.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Jobrequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rresume', models.TextField(default='')),
                ('jobinformation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RPList.jobinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Jobstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ddate', models.TextField(default='')),
                ('Rremarks', models.TextField(default='')),
                ('jobrequirements', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RPList.jobrequirements')),
            ],
        ),
    ]
